### PR TITLE
	use a date to differentiate month/day

### PR DESCRIPTION
**Pull request by paulirish**
jan 1st means both day & month are "1" which makes the cool widget a little harder to grok.

randomly chose march 9, 2015 which can still show the features the same.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Good suggestion. Can you kindly please rebase?

**Comment by marcoscaceres** [comment]
Or remove the white space commit :)

**Comment by marcoscaceres** [comment]
cherry picked it...

**Comment by paulirish** [comment]
what a pro. thx man!

**Pull request merged**
